const express=require('express');
const pool=require('../db');
const {authenticate}=require('../auth');
const storage=require('../documents/storage');
const {audit}=require('../services/audit');
const {notify}=require('../services/notifications');
const router=express.Router();
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
router.use(authenticate);

async function appointmentAccess(id,user,client=pool){
  const r=await client.query(`SELECT a.*,p.user_id provider_user_id,COALESCE(aw.workflow_key,'GENERAL') workflow_key FROM appointments a JOIN provider_profiles p ON p.id=a.provider_id LEFT JOIN appointment_workflows aw ON aw.appointment_id=a.id WHERE a.id=$1`,[id]);if(!r.rowCount)return null;const a=r.rows[0];return user.role==='ADMIN'||[a.client_user_id,a.provider_user_id].includes(user.sub)?a:null;
}
async function consentState(appointmentId,client=pool){const r=await client.query(`SELECT c.user_id,c.decision,u.role,u.first_name,u.last_name,c.decided_at FROM consultation_recording_consents c JOIN users u ON u.id=c.user_id WHERE c.appointment_id=$1`,[appointmentId]);return r.rows;}
async function bothGranted(a,client=pool){const r=await client.query(`SELECT COUNT(DISTINCT user_id)::int count FROM consultation_recording_consents WHERE appointment_id=$1 AND decision='GRANTED' AND user_id=ANY($2::uuid[])`,[a.id,[a.client_user_id,a.provider_user_id]]);return r.rows[0].count===2;}
async function recordingAccess(id,user){const r=await pool.query(`SELECT r.*,a.client_user_id,a.provider_id,a.case_id,p.user_id provider_user_id,COALESCE(aw.workflow_key,'GENERAL') workflow_key,d.original_filename,d.content_type,d.storage_key FROM consultation_recordings r JOIN appointments a ON a.id=r.appointment_id JOIN provider_profiles p ON p.id=a.provider_id LEFT JOIN appointment_workflows aw ON aw.appointment_id=a.id LEFT JOIN secure_documents d ON d.id=r.document_id WHERE r.id=$1`,[id]);if(!r.rowCount)return null;const x=r.rows[0];return user.role==='ADMIN'||[x.client_user_id,x.provider_user_id].includes(user.sub)?x:null;}

router.get('/appointments/:appointmentId',asyncRoute(async(req,res)=>{
  const a=await appointmentAccess(req.params.appointmentId,req.user);if(!a)return res.status(404).json({message:'Appointment not found or access denied.'});const [consents,recordings]=await Promise.all([consentState(a.id),pool.query(`SELECT r.*,d.original_filename,d.size_bytes,t.id transcript_id,t.status transcript_record_status,t.transcript_source,t.language,t.transcript_text FROM consultation_recordings r LEFT JOIN secure_documents d ON d.id=r.document_id LEFT JOIN consultation_transcripts t ON t.recording_id=r.id WHERE r.appointment_id=$1 AND r.status<>'DELETED' ORDER BY r.created_at DESC`,[a.id])]);res.json({consents,consentReady:await bothGranted(a),recordings:recordings.rows});
}));

router.post('/appointments/:appointmentId/consent',asyncRoute(async(req,res)=>{
  const a=await appointmentAccess(req.params.appointmentId,req.user);if(!a)return res.status(404).json({message:'Appointment not found or access denied.'});if(![a.client_user_id,a.provider_user_id].includes(req.user.sub))return res.status(403).json({message:'Only consultation participants can decide recording consent.'});const decision=String(req.body?.decision||'').toUpperCase();if(!['GRANTED','DECLINED','REVOKED'].includes(decision))return res.status(400).json({message:'decision must be GRANTED, DECLINED or REVOKED.'});const row=(await pool.query(`INSERT INTO consultation_recording_consents(appointment_id,user_id,decision,policy_version,evidence) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT(appointment_id,user_id) DO UPDATE SET decision=EXCLUDED.decision,policy_version=EXCLUDED.policy_version,evidence=EXCLUDED.evidence,decided_at=NOW() RETURNING *`,[a.id,req.user.sub,decision,req.body?.policyVersion||'recording-dev-2026-09',JSON.stringify({source:'consultation-room',affirmation:req.body?.affirmation||null})])).rows[0];
  await pool.query(`INSERT INTO consent_records(user_id,appointment_id,consent_type,policy_version,granted,evidence,withdrawn_at) VALUES($1,$2,'CONSULTATION_RECORDING',$3,$4,$5::jsonb,CASE WHEN $4=FALSE THEN NOW() ELSE NULL END)`,[req.user.sub,a.id,row.policy_version,decision==='GRANTED',JSON.stringify({decision,source:'consultation-room'})]);
  const other=req.user.sub===a.client_user_id?a.provider_user_id:a.client_user_id;await notify({userId:other,type:'RECORDING_CONSENT_UPDATED',title:'Consultation recording consent updated',message:`The other participant ${decision==='GRANTED'?'granted':'did not grant'} recording consent.`,relatedType:'APPOINTMENT',relatedId:a.id});await audit({actorUserId:req.user.sub,eventType:'RECORDING_CONSENT_UPDATED',entityType:'APPOINTMENT',entityId:a.id,action:decision,afterState:{decision},req});res.json({consent:row,consentReady:await bothGranted(a)});
}));

router.post('/appointments/:appointmentId/start',asyncRoute(async(req,res)=>{
  const a=await appointmentAccess(req.params.appointmentId,req.user);if(!a)return res.status(404).json({message:'Appointment not found or access denied.'});if(![a.client_user_id,a.provider_user_id].includes(req.user.sub))return res.status(403).json({message:'Only consultation participants can record.'});if(!(await bothGranted(a)))return res.status(409).json({message:'Both client and provider must explicitly consent before recording can start.',code:'RECORDING_CONSENT_REQUIRED'});
  const active=(await pool.query(`SELECT * FROM consultation_recordings WHERE appointment_id=$1 AND status='RECORDING' ORDER BY created_at DESC LIMIT 1`,[a.id])).rows[0];if(active)return res.json({recording:active,reused:true});const type=String(req.body?.recordingType||'AUDIO_VIDEO').toUpperCase();if(!['AUDIO_VIDEO','AUDIO_ONLY'].includes(type))return res.status(400).json({message:'Invalid recording type.'});const r=(await pool.query(`INSERT INTO consultation_recordings(appointment_id,initiated_by,recording_type,status,started_at) VALUES($1,$2,$3,'RECORDING',NOW()) RETURNING *`,[a.id,req.user.sub,type])).rows[0];await audit({actorUserId:req.user.sub,eventType:'CONSULTATION_RECORDING_STARTED',entityType:'APPOINTMENT',entityId:a.id,action:'RECORD_START',afterState:{recordingId:r.id,recordingType:type},req});res.status(201).json({recording:r,reused:false});
}));

router.put('/:recordingId/content',express.raw({type:'*/*',limit:'150mb'}),asyncRoute(async(req,res)=>{
  const r=await recordingAccess(req.params.recordingId,req.user);if(!r)return res.status(404).json({message:'Recording not found or access denied.'});if(r.initiated_by!==req.user.sub&&req.user.role!=='ADMIN')return res.status(403).json({message:'Only the participant who started this recording can upload it.'});if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({message:'Recording content is required.'});const classification=r.workflow_key==='MEDICAL'?'MEDICAL':r.workflow_key==='LEGAL'?'LEGAL_PRIVILEGED':'CONFIDENTIAL';const filename=String(req.headers['x-recording-filename']||`consultation-${r.appointment_id}.webm`).slice(0,255);const c=await pool.connect();try{await c.query('BEGIN');const doc=(await c.query(`INSERT INTO secure_documents(owner_user_id,provider_id,appointment_id,case_id,document_type,purpose,classification,uploaded_role,original_filename,content_type,storage_key,malware_scan_status,encrypted,backup_status) VALUES($1,$2,$3,$4,'CONSULTATION_RECORDING','CONSULTATION_RECORD',$5,$6,$7,$8,'pending','PENDING',FALSE,'PENDING') RETURNING *`,[req.user.sub,r.provider_id,r.appointment_id,r.case_id,classification,req.user.role,filename,req.headers['content-type']||'video/webm'])).rows[0];const saved=await storage.put(doc.id,req.body);await c.query(`UPDATE secure_documents SET storage_key=$2,size_bytes=$3,content_hash=$4,malware_scan_status='CLEAN',backup_key=$5,backup_status=$6 WHERE id=$1`,[doc.id,saved.key,saved.size,saved.hash,saved.backupKey,saved.backupStatus]);const duration=Number(req.headers['x-recording-duration-ms']||0)||null;const updated=(await c.query(`UPDATE consultation_recordings SET status='UPLOADED',document_id=$2,ended_at=NOW(),duration_ms=$3 WHERE id=$1 RETURNING *`,[r.id,doc.id,duration])).rows[0];await c.query(`INSERT INTO document_access_logs(document_id,user_id,action,ip_address,metadata) VALUES($1,$2,'UPLOAD',$3,$4::jsonb)`,[doc.id,req.user.sub,req.ip||null,JSON.stringify({kind:'CONSULTATION_RECORDING',backupStatus:saved.backupStatus})]);await audit({actorUserId:req.user.sub,eventType:'CONSULTATION_RECORDING_STORED',entityType:'APPOINTMENT',entityId:r.appointment_id,action:'RECORD_UPLOAD',afterState:{recordingId:r.id,documentId:doc.id,size:saved.size},req,client:c});await c.query('COMMIT');res.json({recording:updated,documentId:doc.id,backupStatus:saved.backupStatus});}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}
}));

router.put('/:recordingId/transcript',asyncRoute(async(req,res)=>{
  const r=await recordingAccess(req.params.recordingId,req.user);if(!r)return res.status(404).json({message:'Recording not found or access denied.'});const text=String(req.body?.transcriptText||'').trim();if(!text)return res.status(400).json({message:'Transcript text is required.'});if(text.length>500000)return res.status(413).json({message:'Transcript is too large.'});const source=String(req.body?.source||'MANUAL').toUpperCase();if(!['BROWSER_DEMO','MANUAL','EXTERNAL_PROVIDER'].includes(source))return res.status(400).json({message:'Invalid transcript source.'});const status=req.user.role==='PROVIDER'?'READY':'DRAFT';const t=(await pool.query(`INSERT INTO consultation_transcripts(recording_id,appointment_id,language,transcript_text,transcript_source,status) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(recording_id) DO UPDATE SET language=EXCLUDED.language,transcript_text=EXCLUDED.transcript_text,transcript_source=EXCLUDED.transcript_source,status=EXCLUDED.status,updated_at=NOW() RETURNING *`,[r.id,r.appointment_id,req.body?.language||'en-ZA',text,source,status])).rows[0];await pool.query(`UPDATE consultation_recordings SET transcript_status=$2 WHERE id=$1`,[r.id,status==='READY'?'READY':'DRAFT']);await audit({actorUserId:req.user.sub,eventType:'CONSULTATION_TRANSCRIPT_SAVED',entityType:'APPOINTMENT',entityId:r.appointment_id,action:'TRANSCRIPT_SAVE',afterState:{recordingId:r.id,source,status},req});res.json({transcript:t});
}));

router.post('/:recordingId/transcript/review',asyncRoute(async(req,res)=>{
  const r=await recordingAccess(req.params.recordingId,req.user);if(!r)return res.status(404).json({message:'Recording not found or access denied.'});if(req.user.role!=='PROVIDER'&&req.user.role!=='ADMIN')return res.status(403).json({message:'Only the provider or administrator can mark a transcript reviewed.'});const t=(await pool.query(`UPDATE consultation_transcripts SET status='REVIEWED',reviewed_by=$2,reviewed_at=NOW(),updated_at=NOW() WHERE recording_id=$1 RETURNING *`,[r.id,req.user.sub])).rows[0];if(!t)return res.status(404).json({message:'Transcript not found.'});res.json({transcript:t});
}));

module.exports=router;
