const express=require('express');const pool=require('../db');const {getSlots}=require('../calendar/service');const router=express.Router();const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
router.get('/health',asyncRoute(async(_req,res)=>{const db=await pool.query('SELECT NOW() now');res.json({status:'OK',database:'connected',time:db.rows[0].now});}));
router.get('/categories',asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT id,name,slug,description FROM service_categories ORDER BY name`);res.json({categories:r.rows});}));
router.get('/providers',asyncRoute(async(req,res)=>{
  const search=`%${String(req.query.search||'').trim()}%`;const categoryId=req.query.categoryId||null;const city=req.query.city?`%${String(req.query.city).trim()}%`:null;const language=req.query.language?String(req.query.language).trim():null;const maxPrice=req.query.maxPrice?Number(req.query.maxPrice):null;const speciality=req.query.speciality?`%${String(req.query.speciality).trim()}%`:null;
  const r=await pool.query(`SELECT p.id,p.profession,p.biography,p.years_experience,p.city,p.country,p.languages,p.consultation_modes,p.verification_status,u.first_name,u.last_name,c.name category_name,COALESCE(MIN(s.price),0)::float starting_price,COALESCE(MAX(s.currency),'ZAR') currency,m.speciality,l.areas_of_practice,t.specialities,TRUE identity_verified,TRUE registration_verified,TRUE qualification_verified,
    (SELECT COALESCE(AVG(r.rating),0)::float FROM reviews r WHERE r.provider_id=p.id AND r.moderation_status='APPROVED') review_average,
    (SELECT COUNT(*)::int FROM reviews r WHERE r.provider_id=p.id AND r.moderation_status='APPROVED') review_count
    FROM provider_profiles p JOIN users u ON u.id=p.user_id AND u.is_active=TRUE LEFT JOIN service_categories c ON c.id=p.category_id LEFT JOIN provider_services s ON s.provider_id=p.id AND s.is_active=TRUE LEFT JOIN medical_provider_profiles m ON m.provider_id=p.id LEFT JOIN legal_provider_profiles l ON l.provider_id=p.id LEFT JOIN technology_provider_profiles t ON t.provider_id=p.id
    WHERE p.verification_status='VERIFIED' AND ($1::uuid IS NULL OR p.category_id=$1) AND ($3::text IS NULL OR COALESCE(p.city,'') ILIKE $3) AND ($4::text IS NULL OR $4=ANY(p.languages)) AND ($5::numeric IS NULL OR EXISTS(SELECT 1 FROM provider_services ps WHERE ps.provider_id=p.id AND ps.is_active=TRUE AND ps.price<=$5)) AND ($6::text IS NULL OR COALESCE(m.speciality,'') ILIKE $6 OR array_to_string(COALESCE(l.areas_of_practice,'{}'::text[]),',') ILIKE $6 OR array_to_string(COALESCE(t.specialities,'{}'::text[]),',') ILIKE $6) AND (u.first_name ILIKE $2 OR u.last_name ILIKE $2 OR p.profession ILIKE $2 OR COALESCE(p.city,'') ILIKE $2 OR COALESCE(c.name,'') ILIKE $2 OR COALESCE(m.speciality,'') ILIKE $2 OR array_to_string(COALESCE(l.areas_of_practice,'{}'::text[]),',') ILIKE $2 OR array_to_string(COALESCE(t.specialities,'{}'::text[]),',') ILIKE $2)
    GROUP BY p.id,u.first_name,u.last_name,c.name,m.speciality,l.areas_of_practice,t.specialities ORDER BY u.first_name,u.last_name`,[categoryId,search,city,language,maxPrice,speciality]);res.json({providers:r.rows});}));
router.get('/providers/:id',asyncRoute(async(req,res)=>{const p=await pool.query(`SELECT p.*,u.first_name,u.last_name,u.email,c.name category_name FROM provider_profiles p JOIN users u ON u.id=p.user_id LEFT JOIN service_categories c ON c.id=p.category_id WHERE p.id=$1 AND p.verification_status NOT IN('REJECTED','SUSPENDED')`,[req.params.id]);if(!p.rowCount)return res.status(404).json({message:'Provider not found.'});const [services,ver]=await Promise.all([pool.query(`SELECT id,name,description,duration_minutes,price::float,currency FROM provider_services WHERE provider_id=$1 AND is_active=TRUE ORDER BY price,name`,[req.params.id]),pool.query(`SELECT EXISTS(SELECT 1 FROM identity_verifications i WHERE i.provider_id=$1 AND i.status='VERIFIED') identity_verified,EXISTS(SELECT 1 FROM professional_registrations r WHERE r.provider_id=$1 AND r.status='VERIFIED') registration_verified,EXISTS(SELECT 1 FROM professional_qualifications q WHERE q.provider_id=$1 AND q.status='VERIFIED') qualification_verified`,[req.params.id])]);res.json({provider:p.rows[0],services:services.rows,verification:ver.rows[0]});}));
router.get('/providers/:id/slots',asyncRoute(async(req,res)=>{const {date,serviceId}=req.query;if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date||'')))return res.status(400).json({message:'date must use YYYY-MM-DD.'});if(!serviceId)return res.status(400).json({message:'serviceId required.'});const out=await getSlots({providerId:req.params.id,date,serviceId});if(out.notFound)return res.status(404).json({message:'Provider not found.'});if(out.invalidService)return res.status(400).json({message:'Invalid service.'});res.json(out);}));
module.exports=router;
