const express=require('express');
const pool=require('../db');
const {authenticate,signDocumentToken,verifyDocumentToken}=require('../auth');
const storage=require('./storage');
const {audit}=require('../services/audit');

const router=express.Router();
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const ALLOWED_TYPES=new Set(['application/pdf','image/jpeg','image/png','image/webp','image/heic','image/heif','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream']);
const PURPOSES_BY_WORKFLOW={
  MEDICAL:['MEDICAL_INJURY_IMAGE','MEDICAL_REPORT','LAB_RESULT','PRESCRIPTION','REFERRAL','CONSULTATION_SUPPORT'],
  LEGAL:['LEGAL_CLIENT_DOCUMENT','LEGAL_EVIDENCE','LEGAL_DRAFT','LEGAL_SIGNED','CONSULTATION_SUPPORT'],
  TECHNOLOGY:['TECHNOLOGY_ARTIFACT','TECHNICAL_EVIDENCE','CONSULTATION_SUPPORT'],
  GENERAL:['GENERAL_ATTACHMENT','CONSULTATION_SUPPORT']
};

async function appointmentInfo(appointmentId){const r=await pool.query(`SELECT a.client_user_id,a.provider_id,a.case_id,p.user_id provider_user_id,COALESCE(aw.workflow_key,'GENERAL') workflow_key,lm.id legal_matter_id FROM appointments a JOIN provider_profiles p ON p.id=a.provider_id LEFT JOIN appointment_workflows aw ON aw.appointment_id=a.id LEFT JOIN legal_matters lm ON lm.appointment_id=a.id WHERE a.id=$1`,[appointmentId]);return r.rows[0]||null;}
async function appointmentAccess(appointmentId,user){const a=await appointmentInfo(appointmentId);if(!a)return null;if(user.role==='ADMIN'||[a.client_user_id,a.provider_user_id].includes(user.sub))return a;return null;}
async function caseAccess(caseId,user,requireDocuments=true){const r=await pool.query(`SELECT c.*,op.user_id origin_user_id,cp.user_id current_user_id,pga.scope FROM consultation_cases c JOIN provider_profiles op ON op.id=c.originating_provider_id JOIN provider_profiles cp ON cp.id=c.current_provider_id LEFT JOIN provider_profiles me ON me.user_id=$2 LEFT JOIN case_provider_access pga ON pga.case_id=c.id AND pga.provider_id=me.id AND pga.revoked_at IS NULL AND (pga.valid_until IS NULL OR pga.valid_until>NOW()) WHERE c.id=$1`,[caseId,user.sub]);if(!r.rowCount)return null;const c=r.rows[0];if(user.role==='ADMIN'||c.client_user_id===user.sub||c.origin_user_id===user.sub||c.current_user_id===user.sub)return c;if(c.scope&&(!requireDocuments||c.scope.documents===true))return c;return null;}
async function getDoc(id){const r=await pool.query(`SELECT d.*,a.client_user_id,p.user_id provider_user_id,c.client_user_id case_client_user_id,op.user_id case_origin_user_id,cp.user_id case_current_user_id FROM secure_documents d LEFT JOIN appointments a ON a.id=d.appointment_id LEFT JOIN provider_profiles p ON p.id=COALESCE(d.provider_id,a.provider_id) LEFT JOIN consultation_cases c ON c.id=d.case_id LEFT JOIN provider_profiles op ON op.id=c.originating_provider_id LEFT JOIN provider_profiles cp ON cp.id=c.current_provider_id WHERE d.id=$1 AND d.deleted_at IS NULL`,[id]);return r.rows[0]||null;}
async function docAccess(doc,user){
  if(user.role==='ADMIN'||doc.owner_user_id===user.sub)return true;
  if(doc.classification==='INTERNAL')return doc.provider_user_id===user.sub;
  if(doc.appointment_id&&[doc.client_user_id,doc.provider_user_id].includes(user.sub))return true;
  if(doc.case_id&&await caseAccess(doc.case_id,user,true))return true;
  return false;
}
function defaultClassification(workflow,role,purpose){if(purpose==='LEGAL_DRAFT'&&role==='PROVIDER')return'INTERNAL';if(workflow==='LEGAL')return'LEGAL_PRIVILEGED';if(workflow==='MEDICAL')return'MEDICAL';return'CONFIDENTIAL';}

router.post('/intents',authenticate,asyncRoute(async(req,res)=>{
  const b=req.body||{};if(!b.originalFilename)return res.status(400).json({message:'originalFilename is required.'});let appointment=null;let cc=null;let workflow=String(b.workflowKey||'GENERAL').toUpperCase();let providerId=b.providerId||null;let caseId=b.caseId||null;let legalMatterId=b.legalMatterId||null;
  if(b.appointmentId){appointment=await appointmentAccess(b.appointmentId,req.user);if(!appointment)return res.status(403).json({message:'You do not have access to that appointment.'});workflow=appointment.workflow_key;providerId=appointment.provider_id;caseId=caseId||appointment.case_id;legalMatterId=legalMatterId||appointment.legal_matter_id;}
  if(caseId){cc=await caseAccess(caseId,req.user,true);if(!cc)return res.status(403).json({message:'You do not have document access to that case.'});workflow=cc.workflow_key;providerId=providerId||cc.current_provider_id;}
  const purpose=String(b.purpose||b.documentType||'CONSULTATION_SUPPORT').toUpperCase();const allowed=PURPOSES_BY_WORKFLOW[workflow]||PURPOSES_BY_WORKFLOW.GENERAL;if(!allowed.includes(purpose)&&!['CONSULTATION_RECORDING','TRANSCRIPT'].includes(purpose))return res.status(400).json({message:`${purpose} is not an allowed ${workflow} document purpose.`,allowedPurposes:allowed});
  const classification=b.classification||defaultClassification(workflow,req.user.role,purpose);const r=await pool.query(`INSERT INTO secure_documents(owner_user_id,provider_id,appointment_id,case_id,legal_matter_id,document_type,purpose,classification,uploaded_role,original_filename,content_type,storage_key,malware_scan_status,encrypted,backup_status) VALUES($1,$2,$3,$4,$5,$6,$6,$7,$8,$9,$10,$11,'PENDING',FALSE,'PENDING') RETURNING *`,[req.user.sub,providerId,b.appointmentId||null,caseId,legalMatterId,purpose,classification,req.user.role,b.originalFilename,b.contentType||'application/octet-stream',`pending/${Date.now()}`]);await audit({actorUserId:req.user.sub,eventType:'DOCUMENT_INTENT_CREATED',entityType:'DOCUMENT',entityId:r.rows[0].id,action:'CREATE',afterState:{classification,purpose,workflow,caseId},req});res.status(201).json({document:r.rows[0],uploadUrl:`/api/documents/${r.rows[0].id}/content`,maxBytes:25*1024*1024,allowedContentTypes:[...ALLOWED_TYPES]});
}));

router.put('/:id/content',authenticate,express.raw({type:'*/*',limit:'25mb'}),asyncRoute(async(req,res)=>{
  const doc=await getDoc(req.params.id);if(!doc)return res.status(404).json({message:'Document not found.'});if(doc.owner_user_id!==req.user.sub&&req.user.role!=='ADMIN')return res.status(403).json({message:'Only the document owner can upload this content.'});if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({message:'Document content is required.'});const contentType=String(req.headers['content-type']||doc.content_type||'application/octet-stream').split(';')[0];if(!ALLOWED_TYPES.has(contentType))return res.status(415).json({message:'This file type is not allowed for consultation documents.'});const saved=await storage.put(doc.id,req.body);const r=(await pool.query(`UPDATE secure_documents SET storage_key=$2,size_bytes=$3,content_hash=$4,content_type=$5,malware_scan_status='CLEAN',backup_key=$6,backup_status=$7 WHERE id=$1 RETURNING *`,[doc.id,saved.key,saved.size,saved.hash,contentType,saved.backupKey,saved.backupStatus])).rows[0];await pool.query(`INSERT INTO document_access_logs(document_id,user_id,action,ip_address,metadata) VALUES($1,$2,'UPLOAD',$3,$4::jsonb)`,[doc.id,req.user.sub,req.ip||null,JSON.stringify({scanner:'DEMO_CLEAN',backupStatus:saved.backupStatus})]);res.json({document:r,message:'Stored in the local private development vault with a second local backup copy. Malware scan is simulated CLEAN.'});
}));

router.get('/',authenticate,asyncRoute(async(req,res)=>{
  const appointmentId=req.query.appointmentId||null;const caseId=req.query.caseId||null;if(appointmentId&&!(await appointmentAccess(appointmentId,req.user)))return res.status(403).json({message:'Appointment access denied.'});if(caseId&&!(await caseAccess(caseId,req.user,true)))return res.status(403).json({message:'Case document access denied.'});
  const r=await pool.query(`SELECT d.*,a.client_user_id,p.user_id provider_user_id FROM secure_documents d LEFT JOIN appointments a ON a.id=d.appointment_id LEFT JOIN provider_profiles p ON p.id=COALESCE(d.provider_id,a.provider_id) WHERE d.deleted_at IS NULL AND ($1::uuid IS NULL OR d.appointment_id=$1) AND ($2::uuid IS NULL OR d.case_id=$2) ORDER BY d.created_at DESC LIMIT 300`,[appointmentId,caseId]);const docs=[];for(const d of r.rows)if(await docAccess(d,req.user))docs.push(d);res.json({documents:docs});
}));

router.post('/:id/download-token',authenticate,asyncRoute(async(req,res)=>{const doc=await getDoc(req.params.id);if(!doc)return res.status(404).json({message:'Document not found.'});if(!(await docAccess(doc,req.user)))return res.status(403).json({message:'You do not have access to this document.'});res.json({downloadToken:signDocumentToken({userId:req.user.sub,documentId:doc.id}),expiresInSeconds:300,url:`/api/documents/${doc.id}/content?token=SIGNED_TOKEN`});}));
router.get('/:id/content',asyncRoute(async(req,res)=>{let payload;try{payload=verifyDocumentToken(req.query.token||'');}catch{return res.status(401).json({message:'A valid short-lived document token is required.'});}if(payload.documentId!==req.params.id)return res.status(401).json({message:'Invalid document token.'});const doc=await getDoc(req.params.id);if(!doc)return res.status(404).json({message:'Document not found.'});const fakeUser={sub:payload.sub,role:'TOKEN'};if(!(await docAccess(doc,fakeUser)))return res.status(403).json({message:'Document access denied.'});const data=await storage.read(doc.storage_key);await pool.query(`INSERT INTO document_access_logs(document_id,user_id,action,metadata) VALUES($1,$2,'DOWNLOAD',$3::jsonb)`,[doc.id,payload.sub,JSON.stringify({backupFallbackSupported:true})]);res.setHeader('Content-Type',doc.content_type||'application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename="${String(doc.original_filename).replace(/"/g,'')}"`);res.send(data);}));
module.exports=router;
