require('dotenv').config();
const http=require('http');
const crypto=require('crypto');
const express=require('express');
const cors=require('cors');
const {rateLimit}=require('./services/security');
const publicRouter=require('./routes/public');
const authRouter=require('./routes/auth');
const appointmentsRouter=require('./routes/appointments');
const notificationsRouter=require('./routes/notifications');
const providerRouter=require('./routes/provider');
const calendarRouter=require('./calendar/routes');
const paymentsRouter=require('./payments/routes');
const consultationsRouter=require('./consultations/routes');
const verificationRouter=require('./verification/routes');
const adminRouter=require('./admin/routes');
const serviceRequestsRouter=require('./service-requests/routes');
const workflowsRouter=require('./workflows/routes');
const privacyRouter=require('./privacy/routes');
const documentsRouter=require('./documents/routes');
const reviewsRouter=require('./reviews/routes');
const organizationsRouter=require('./organizations/routes');
const billingRouter=require('./billing/routes');
const casesRouter=require('./cases/routes');
const recordingsRouter=require('./recordings/routes');
const {processNotificationJobs}=require('./services/notification-worker');
const {expireProviderClaims}=require('./service-requests/service');
const {attachConsultationSockets}=require('./consultations/socket');
const {runReverification}=require('./verification/reverification-worker');

if(!process.env.JWT_SECRET) throw new Error('JWT_SECRET is required. Set it in server/.env.');
const app=express();const PORT=Number(process.env.PORT||5000);
app.set('trust proxy',1);
app.use((req,res,next)=>{const started=Date.now();req.requestId=String(req.headers['x-request-id']||crypto.randomUUID());res.setHeader('X-Request-Id',req.requestId);res.on('finish',()=>console.log(JSON.stringify({ts:new Date().toISOString(),level:'INFO',event:'HTTP_REQUEST',requestId:req.requestId,method:req.method,path:req.originalUrl,status:res.statusCode,durationMs:Date.now()-started,userId:req.user?.sub||null})));next();});
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173',credentials:true}));
app.use(express.json({limit:'1mb'}));
app.use(rateLimit({windowMs:60_000,max:240}));

app.use('/api',publicRouter);
app.use('/api/auth',authRouter);
app.use('/api/appointments',appointmentsRouter);
app.use('/api/notifications',notificationsRouter);
app.use('/api/provider/calendar',calendarRouter);
app.use('/api/provider',providerRouter);
app.use('/api/payments',paymentsRouter);
app.use('/api/consultations',consultationsRouter);
app.use('/api/verification',verificationRouter);
app.use('/api/admin',adminRouter);
app.use('/api/service-requests',serviceRequestsRouter);
app.use('/api/workflows',workflowsRouter);
app.use('/api/privacy',privacyRouter);
app.use('/api/documents',documentsRouter);
app.use('/api/reviews',reviewsRouter);
app.use('/api/organizations',organizationsRouter);
app.use('/api/billing',billingRouter);
app.use('/api/cases',casesRouter);
app.use('/api/recordings',recordingsRouter);

app.use((err,_req,res,_next)=>{
  console.error(JSON.stringify({ts:new Date().toISOString(),level:'ERROR',event:'UNHANDLED_ERROR',requestId:_req.requestId||null,message:err.message,code:err.code||null,stack:process.env.NODE_ENV==='production'?undefined:err.stack}));
  if(err.code==='22P02')return res.status(400).json({message:'Invalid identifier or request value.'});
  res.status(err.statusCode||500).json({message:err.statusCode?err.message:'Unexpected server error.',requestId:_req.requestId});
});
const server=http.createServer(app);attachConsultationSockets(server);
const timeoutSweep=setInterval(()=>expireProviderClaims().catch(err=>console.error('Service request timeout sweep failed:',err)),60_000);
timeoutSweep.unref?.();
const notificationSweep=setInterval(()=>processNotificationJobs().catch(err=>console.error('Notification worker failed:',err)),15_000);
notificationSweep.unref?.();
const reverificationSweep=setInterval(()=>runReverification().catch(err=>console.error('Professional re-verification worker failed:',err)),60*60*1000);
reverificationSweep.unref?.();
server.listen(PORT,()=>console.log(`ConsultHub API running on http://localhost:${PORT}`));
