async function postVerification(url,apiKey,payload,label){
  if(!url)throw Object.assign(new Error(`${label} production verification endpoint is not configured.`),{statusCode:503});
  const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(apiKey?{'authorization':`Bearer ${apiKey}`}:{})},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});
  const text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={raw:text.slice(0,500)}}
  if(!response.ok)throw Object.assign(new Error(`${label} verification provider returned HTTP ${response.status}.`),{statusCode:502,providerResponse:body});
  return body;
}
function normalizeIdentity(body){return {provider:body.provider||'PRODUCTION_IDENTITY_PROVIDER',reference:body.reference||body.id||null,verified:Boolean(body.verified),documentAuthentic:Boolean(body.documentAuthentic??body.document_authentic),livenessPassed:Boolean(body.livenessPassed??body.liveness_passed),faceMatchPassed:Boolean(body.faceMatchPassed??body.face_match_passed),confidence:Number(body.confidence||0),message:body.message||'Identity verification completed.'};}
function normalizeRegistry(body,regulatoryBody,registrationNumber){return {body:regulatoryBody,source:body.source||`PRODUCTION_${regulatoryBody}`,registrationNumber,found:Boolean(body.found??true),nameMatch:Boolean(body.nameMatch??body.name_match),active:Boolean(body.active),verified:Boolean(body.verified),record:body.record||{status:body.status||'UNKNOWN',category:body.category||null,practitionerType:body.practitionerType||null},message:body.message||'Professional registry verification completed.'};}
async function verifyIdentity(payload){return normalizeIdentity(await postVerification(process.env.IDENTITY_VERIFICATION_URL,process.env.IDENTITY_VERIFICATION_API_KEY,payload,'Identity'));}
async function verifyRegistry(regulatoryBody,payload){const key=String(regulatoryBody||'').toUpperCase();const url=process.env[`${key}_VERIFICATION_URL`]||process.env.PROFESSIONAL_REGISTRY_VERIFICATION_URL;const apiKey=process.env[`${key}_VERIFICATION_API_KEY`]||process.env.PROFESSIONAL_REGISTRY_VERIFICATION_API_KEY;return normalizeRegistry(await postVerification(url,apiKey,{regulatoryBody:key,...payload},`${key} registry`),key,payload.registrationNumber);}
async function verifyQualification(payload){const body=await postVerification(process.env.QUALIFICATION_VERIFICATION_URL,process.env.QUALIFICATION_VERIFICATION_API_KEY,payload,'Qualification');return {verified:Boolean(body.verified),source:body.source||'PRODUCTION_QUALIFICATION_PROVIDER',reference:body.reference||body.id||null,message:body.message||'Qualification verification completed.',raw:body};}
module.exports={verifyIdentity,verifyRegistry,verifyQualification};
