const express=require('express');const pool=require('../db');const {authenticate,authorize,authorizeAdmin,adminRoles}=require('../auth');
const router=express.Router();const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);router.use(authenticate,authorize('ADMIN'));
const {notify}=require('../services/notifications');
router.get('/overview',asyncRoute(async(_req,res)=>{
  const [users,providers,appointments,payments,cases,security,serviceRequests]=await Promise.all([
    pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE is_active)::int active,COUNT(*) FILTER(WHERE locked_until>NOW())::int locked FROM users`),
    pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE verification_status='PENDING')::int pending,COUNT(*) FILTER(WHERE verification_status='VERIFIED')::int verified,COUNT(*) FILTER(WHERE verification_status='SUSPENDED')::int suspended FROM provider_profiles`),
    pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='CONFIRMED' AND starts_at>=NOW())::int upcoming,COUNT(*) FILTER(WHERE status='EXPIRED')::int expired FROM appointments`),
    pool.query(`SELECT COUNT(*)::int total,COALESCE(SUM(amount) FILTER(WHERE status='PAID'),0)::float paid_value,COUNT(*) FILTER(WHERE status='FAILED')::int failed FROM payments`),
    pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status IN('OPEN','IN_REVIEW'))::int open,COUNT(*) FILTER(WHERE priority IN('HIGH','CRITICAL') AND status IN('OPEN','IN_REVIEW'))::int urgent FROM compliance_cases`),
    pool.query(`SELECT COUNT(*) FILTER(WHERE created_at>NOW()-INTERVAL '24 hours')::int last_24h,COUNT(*) FILTER(WHERE severity IN('HIGH','CRITICAL') AND created_at>NOW()-INTERVAL '7 days')::int high_risk_7d FROM security_events`),
    pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='OPEN')::int open,COUNT(*) FILTER(WHERE status='CLAIMED')::int claimed,COUNT(*) FILTER(WHERE status='QUOTED')::int quoted,COUNT(*) FILTER(WHERE status='PROVIDER_TIMEOUT')::int timed_out,COUNT(*) FILTER(WHERE status='ACCEPTED')::int accepted FROM service_requests`)
  ]);res.json({users:users.rows[0],providers:providers.rows[0],appointments:appointments.rows[0],payments:payments.rows[0],cases:cases.rows[0],security:security.rows[0],serviceRequests:serviceRequests.rows[0]});
}));
router.get('/users',authorizeAdmin('users:read'),asyncRoute(async(req,res)=>{const q=`%${String(req.query.search||'')}%`;const r=await pool.query(`SELECT id,first_name,last_name,email,phone,role,is_active,email_verified,mfa_enabled,failed_login_attempts,locked_until,last_login_at,created_at FROM users WHERE email ILIKE $1 OR first_name ILIKE $1 OR last_name ILIKE $1 ORDER BY created_at DESC LIMIT 200`,[q]);res.json({users:r.rows});}));
router.patch('/users/:id',authorizeAdmin('users:support'),asyncRoute(async(req,res)=>{const {isActive,unlock}=req.body;const r=await pool.query(`UPDATE users SET is_active=COALESCE($2,is_active),locked_until=CASE WHEN $3 THEN NULL ELSE locked_until END,failed_login_attempts=CASE WHEN $3 THEN 0 ELSE failed_login_attempts END,updated_at=NOW() WHERE id=$1 RETURNING id,first_name,last_name,email,role,is_active,locked_until`,[req.params.id,typeof isActive==='boolean'?isActive:null,Boolean(unlock)]);if(!r.rowCount)return res.status(404).json({message:'User not found.'});res.json({user:r.rows[0]});}));
router.get('/security-events',authorizeAdmin('security:read'),asyncRoute(async(req,res)=>{const severity=req.query.severity||null;const r=await pool.query(`SELECT s.*,u.email,u.first_name,u.last_name FROM security_events s LEFT JOIN users u ON u.id=s.user_id WHERE ($1::text IS NULL OR s.severity=$1) ORDER BY s.created_at DESC LIMIT 250`,[severity]);res.json({events:r.rows});}));
router.get('/payments',authorizeAdmin('payments:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT pay.*,a.booking_reference,u.email client_email,pu.email provider_email FROM payments pay JOIN appointments a ON a.id=pay.appointment_id JOIN users u ON u.id=pay.client_user_id JOIN provider_profiles pp ON pp.id=pay.provider_id JOIN users pu ON pu.id=pp.user_id ORDER BY pay.created_at DESC LIMIT 250`);res.json({payments:r.rows});}));
router.get('/appointments',authorizeAdmin('appointments:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT a.*,cu.email client_email,pu.email provider_email,s.name service_name FROM appointments a JOIN users cu ON cu.id=a.client_user_id JOIN provider_profiles p ON p.id=a.provider_id JOIN users pu ON pu.id=p.user_id JOIN provider_services s ON s.id=a.service_id ORDER BY a.created_at DESC LIMIT 250`);res.json({appointments:r.rows});}));
router.get('/compliance-cases',authorizeAdmin('cases:read'),asyncRoute(async(req,res)=>{const status=req.query.status||null;const r=await pool.query(`SELECT c.*,u.email subject_email,p.profession,au.email assigned_admin_email FROM compliance_cases c LEFT JOIN users u ON u.id=c.subject_user_id LEFT JOIN provider_profiles p ON p.id=c.provider_id LEFT JOIN users au ON au.id=c.assigned_admin_id WHERE ($1::text IS NULL OR c.status=$1) ORDER BY CASE c.priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,c.created_at DESC`,[status]);res.json({cases:r.rows});}));
router.post('/compliance-cases',authorizeAdmin('cases:write'),asyncRoute(async(req,res)=>{const {subjectUserId,providerId,caseType,priority='MEDIUM',summary,details}=req.body;if(!caseType||!summary)return res.status(400).json({message:'caseType and summary are required.'});const r=await pool.query(`INSERT INTO compliance_cases(subject_user_id,provider_id,case_type,priority,summary,details,created_by,assigned_admin_id) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING *`,[subjectUserId||null,providerId||null,caseType,priority,summary,details||null,req.user.sub]);res.status(201).json({case:r.rows[0]});}));
router.patch('/compliance-cases/:id',authorizeAdmin('cases:write'),asyncRoute(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['OPEN','IN_REVIEW','RESOLVED','CLOSED'].includes(status))return res.status(400).json({message:'Invalid case status.'});const r=await pool.query(`UPDATE compliance_cases SET status=$2,resolution_notes=COALESCE($3,resolution_notes),assigned_admin_id=COALESCE(assigned_admin_id,$4),updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,status,req.body.resolutionNotes||null,req.user.sub]);if(!r.rowCount)return res.status(404).json({message:'Case not found.'});res.json({case:r.rows[0]});}));

router.get('/service-requests',authorizeAdmin('requests:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT sr.*,c.name category_name,cu.email client_email,pu.email provider_email,q.amount quote_amount,q.currency quote_currency FROM service_requests sr JOIN service_categories c ON c.id=sr.category_id JOIN users cu ON cu.id=sr.client_user_id LEFT JOIN provider_profiles p ON p.id=sr.assigned_provider_id LEFT JOIN users pu ON pu.id=p.user_id LEFT JOIN LATERAL (SELECT * FROM service_request_quotes sq WHERE sq.service_request_id=sr.id ORDER BY sq.created_at DESC LIMIT 1) q ON TRUE ORDER BY sr.created_at DESC LIMIT 250`);res.json({serviceRequests:r.rows});}));

router.get('/roles/me',asyncRoute(async(req,res)=>res.json({roles:await adminRoles(req.user.sub)})));
router.get('/roles',authorizeAdmin('*'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT ar.*,u.email,u.first_name,u.last_name FROM admin_role_assignments ar JOIN users u ON u.id=ar.user_id ORDER BY u.email,ar.admin_role`);res.json({assignments:r.rows});}));
router.post('/roles',authorizeAdmin('*'),asyncRoute(async(req,res)=>{const role=String(req.body.adminRole||'').toUpperCase();if(!['SUPER_ADMIN','VERIFICATION_ADMIN','SUPPORT_AGENT','FINANCE_ADMIN','COMPLIANCE_ADMIN'].includes(role))return res.status(400).json({message:'Invalid admin role.'});const u=await pool.query(`SELECT id,role FROM users WHERE LOWER(email)=LOWER($1)`,[req.body.email]);if(!u.rowCount||u.rows[0].role!=='ADMIN')return res.status(400).json({message:'Target account must exist and have ADMIN role.'});const r=await pool.query(`INSERT INTO admin_role_assignments(user_id,admin_role,granted_by) VALUES($1,$2,$3) ON CONFLICT(user_id,admin_role) DO NOTHING RETURNING *`,[u.rows[0].id,role,req.user.sub]);res.status(201).json({assignment:r.rows[0]||{user_id:u.rows[0].id,admin_role:role}});}));
router.delete('/roles/:id',authorizeAdmin('*'),asyncRoute(async(req,res)=>{const r=await pool.query(`DELETE FROM admin_role_assignments WHERE id=$1 RETURNING *`,[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Role assignment not found.'});res.json({message:'Role removed.'});}));

router.get('/privacy-requests',authorizeAdmin('privacy:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT pr.*,u.email FROM privacy_requests pr JOIN users u ON u.id=pr.user_id ORDER BY pr.created_at DESC`);res.json({requests:r.rows});}));
router.patch('/privacy-requests/:id',authorizeAdmin('privacy:write'),asyncRoute(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['OPEN','IN_REVIEW','COMPLETED','REJECTED'].includes(status))return res.status(400).json({message:'Invalid status.'});const r=await pool.query(`UPDATE privacy_requests SET status=$2,resolution_notes=COALESCE($3,resolution_notes),assigned_admin_id=$4,completed_at=CASE WHEN $2 IN('COMPLETED','REJECTED') THEN NOW() ELSE NULL END WHERE id=$1 RETURNING *`,[req.params.id,status,req.body.resolutionNotes||null,req.user.sub]);if(!r.rowCount)return res.status(404).json({message:'Privacy request not found.'});res.json({request:r.rows[0]});}));
router.get('/breaches',authorizeAdmin('privacy:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT * FROM breach_incidents ORDER BY discovered_at DESC`);res.json({incidents:r.rows});}));
router.patch('/breaches/:id',authorizeAdmin('privacy:write'),asyncRoute(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['OPEN','CONTAINED','INVESTIGATING','RESOLVED','CLOSED'].includes(status))return res.status(400).json({message:'Invalid incident status.'});const r=await pool.query(`UPDATE breach_incidents SET status=$2,assigned_admin_id=COALESCE(assigned_admin_id,$3),regulator_notification_required=COALESCE($4,regulator_notification_required),subject_notification_required=COALESCE($5,subject_notification_required),containment_notes=COALESCE($6,containment_notes),resolution_notes=COALESCE($7,resolution_notes),updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,status,req.user.sub,typeof req.body.regulatorNotificationRequired==='boolean'?req.body.regulatorNotificationRequired:null,typeof req.body.subjectNotificationRequired==='boolean'?req.body.subjectNotificationRequired:null,req.body.containmentNotes||null,req.body.resolutionNotes||null]);if(!r.rowCount)return res.status(404).json({message:'Incident not found.'});res.json({incident:r.rows[0]});}));
router.get('/document-access',authorizeAdmin('documents:audit'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT l.*,d.original_filename,d.classification,u.email FROM document_access_logs l JOIN secure_documents d ON d.id=l.document_id LEFT JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT 500`);res.json({events:r.rows});}));
router.get('/audit-events',authorizeAdmin('audit:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT a.*,u.email actor_email FROM audit_events a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 500`);res.json({events:r.rows});}));
router.get('/reviews',authorizeAdmin('cases:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT r.*,cu.email client_email,pu.email provider_email FROM reviews r JOIN users cu ON cu.id=r.client_user_id JOIN provider_profiles p ON p.id=r.provider_id JOIN users pu ON pu.id=p.user_id ORDER BY r.created_at DESC`);res.json({reviews:r.rows});}));
router.patch('/reviews/:id',authorizeAdmin('cases:write'),asyncRoute(async(req,res)=>{const status=String(req.body.status||'').toUpperCase();if(!['PENDING','APPROVED','REJECTED','HIDDEN'].includes(status))return res.status(400).json({message:'Invalid review moderation status.'});const r=await pool.query(`UPDATE reviews SET moderation_status=$2,updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id,status]);if(!r.rowCount)return res.status(404).json({message:'Review not found.'});const review=r.rows[0];await notify({userId:review.client_user_id,type:'REVIEW_MODERATION',title:`Review ${status.toLowerCase()}`,message:status==='APPROVED'?'Your rating and comment are now visible on the provider profile.':`Your review status is now ${status}.`,relatedType:'REVIEW',relatedId:review.id});res.json({review});}));
router.get('/refunds',authorizeAdmin('payments:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT * FROM refunds ORDER BY created_at DESC LIMIT 250`);res.json({refunds:r.rows});}));
router.get('/payouts',authorizeAdmin('payments:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT po.*,u.email provider_email FROM provider_payouts po JOIN provider_profiles p ON p.id=po.provider_id JOIN users u ON u.id=p.user_id ORDER BY po.created_at DESC LIMIT 250`);res.json({payouts:r.rows});}));

router.get('/fee-rules',authorizeAdmin('payments:read'),asyncRoute(async(_req,res)=>{const r=await pool.query(`SELECT f.*,c.name category_name FROM platform_fee_rules f LEFT JOIN service_categories c ON c.id=f.category_id ORDER BY f.effective_from DESC`);res.json({feeRules:r.rows});}));
router.post('/fee-rules',authorizeAdmin('payments:write'),asyncRoute(async(req,res)=>{const {name,percentage=0,fixedAmount=0,currency='ZAR',categoryId,effectiveFrom}=req.body;if(!name)return res.status(400).json({message:'Fee rule name is required.'});const r=await pool.query(`INSERT INTO platform_fee_rules(name,percentage,fixed_amount,currency,category_id,effective_from) VALUES($1,$2,$3,$4,$5,COALESCE($6::timestamptz,NOW())) RETURNING *`,[name,Number(percentage),Number(fixedAmount),currency,categoryId||null,effectiveFrom||null]);res.status(201).json({feeRule:r.rows[0]});}));
router.patch('/fee-rules/:id',authorizeAdmin('payments:write'),asyncRoute(async(req,res)=>{const r=await pool.query(`UPDATE platform_fee_rules SET is_active=COALESCE($2,is_active),effective_to=COALESCE($3::timestamptz,effective_to) WHERE id=$1 RETURNING *`,[req.params.id,typeof req.body.isActive==='boolean'?req.body.isActive:null,req.body.effectiveTo||null]);if(!r.rowCount)return res.status(404).json({message:'Fee rule not found.'});res.json({feeRule:r.rows[0]});}));

module.exports=router;
